baseURL = 'https://kozmof.github.io/'
languageCode = 'ja'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'kozmof.github.io'
theme = "bare"

[params]
author = "kozmof"
description = "log"
includeAuthorInTitle = true

# https://materialdesignicons.com/
[[params.social]]
icon = "twitter"
url = "https://twitter.com/kozmof"
