baseURL = 'https://kozmof.github.io/'
languageCode = 'ja'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'kozmof.github.io'
theme = "archie"

[params]
author = "kozmof"
description = "log"
includeAuthorInTitle = true
mode="toggle"
customcss = ["css/custom.css"]
historyBaseURL = "https://github.com/kozmof/kozmof.github.io/commits/main/content/"
defaultModelHDRPath = "hdr/lake_pier_1k.hdr"
defaultModelMinHeight = "500px"

# https://materialdesignicons.com/
[[params.social]]
icon = "twitter"
url = "https://twitter.com/kozmof"

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1